[package]
name = "cargo-elfpak"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Cargo subcommand for packaging a binary and its Linux runtime closure"

[lib]
name = "cargo_elfpak"
path = "src/lib.rs"

[[bin]]
name = "cargo-elfpak"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
elfpak = { path = "../elfpak", version = "0.2.0" }
anyhow.workspace = true
cargo_metadata = "0.23.1"
clap.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
