[package]
name = "elfpak"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[[bin]]
name = "elfpak"
path = "src/main.rs"

[dependencies]
elfpak-core.workspace = true
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true

[dev-dependencies]
elfpak-core.workspace = true
serde_json.workspace = true
tempfile.workspace = true
